{{- if .Values.createConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: file-server-clean-config
  labels:
    {{- include "file-server.labels" . | nindent 4 }}
    velero.io/backup-app: fileserver
data:
  Clean.conf: |
    # Spacify folder path and the number of files kept, e.g.
    # /data/download:100
{{- end }}
