apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "file-server.fullname" . }}
spec:
  schedule: "{{ .Values.houseKeeping.schedule }}"
  concurrencyPolicy: Forbid
  timeZone: {{ .Values.houseKeeping.timeZone }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - bash
                - -c
                - curl -s -X POST http://{{ include "file-server.fullname" . }}/_admin/housekeeping | jq .
              volumeMounts:
                - mountPath: /data
                  name: {{ include "file-server.fullname" . }}-data
          restartPolicy: Never
          volumes:
            - name: {{ include "file-server.fullname" . }}-data
              {{- if .Values.persistence.enabled }}
              persistentVolumeClaim:
                claimName: {{ .Values.persistence.existingClaim | default (printf "%s-%s" (include "file-server.fullname" .) "data") }}
              {{- else }}
              emptyDir: { }
              {{- end }}
