apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "file-server.fullname" . }}
  labels:
    {{- include "file-server.labels" . | nindent 4 }}
    velero.io/backup-app: fileserver
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "file-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "file-server.selectorLabels" . | nindent 8 }}
        velero.io/backup-app: fileserver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "file-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: {{ include "file-server.fullname" . }}-data
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: file-server-oidc
        {{- if .Values.samba.enabled }}
        - name: samba
          image: "{{ .Values.samba.image.repository }}:{{ .Values.samba.image.tag }}"
          imagePullPolicy: {{ .Values.samba.image.pullPolicy }}
          ports:
            - name: smb
              containerPort: 445
              protocol: TCP
          env:
            - name: ACCOUNT_{{ .Values.samba.username }}
              value: {{ .Values.samba.password | quote }}
            {{- if .Values.samba.uid }}
            - name: UID_{{ .Values.samba.username }}
              value: {{ .Values.samba.uid | quote }}
            {{- end }}
            {{- if .Values.samba.gid }}
            - name: GROUP_{{ .Values.samba.username }}
              value: {{ .Values.samba.gid | quote }}
            {{- end }}
            - name: SAMBA_VOLUME_CONFIG_{{ .Values.samba.shareName }}
              value: "[{{ .Values.samba.shareName }}]; path = {{ .Values.samba.sharePath }}; valid users = {{ .Values.samba.username }}; read only = {{ if .Values.samba.readOnly }}yes{{ else }}no{{ end }}; browseable = yes; guest ok = no"
          volumeMounts:
            - name: {{ include "file-server.fullname" . }}-data
              mountPath: /data
          resources:
            {{- toYaml .Values.samba.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "file-server.fullname" . }}-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-%s" (include "file-server.fullname" .) "data") }}
          {{- else }}
          emptyDir: { }
          {{- end }}
